### ISSUE TITLE
Tests are failing in eslint-config package

### ISSUE THREAD

**Issue by alansemenov** [enonic/enonic-npm-modules#301]
Tests are failing in `eslint-config` package when running `npm test` in the root:
```
 FAIL  packages/eslint-config/test/eslint.test.ts
  ● Default › eslint-config

    Failed to load plugin '@typescript-eslint' declared in 'CLIOptions#overrides[0] » /Users/ase/dev/enonic-npm-modules/packages/eslint-config/typescript.js': Cannot find module 'eslint/use-at-your-own-risk' from 'node_modules/@typescript-eslint/eslint-plugin/dist/util/getESLintCoreRule.js'

    Require stack:
      node_modules/@typescript-eslint/eslint-plugin/dist/rules/brace-style.js
      node_modules/@typescript-eslint/eslint-plugin/dist/rules/index.js
      node_modules/@typescript-eslint/eslint-plugin/dist/index.js
      packages/eslint-config/node_modules/@eslint/eslintrc/dist/eslintrc.cjs
      packages/eslint-config/node_modules/eslint/lib/cli-engine/cli-engine.js
      packages/eslint-config/node_modules/eslint/lib/eslint/eslint.js
      packages/eslint-config/node_modules/eslint/lib/eslint/index.js
      packages/eslint-config/node_modules/eslint/lib/api.js
      packages/eslint-config/test/eslint.test.ts

    Referenced from: /Users/ase/dev/enonic-npm-modules/packages/eslint-config/typescript.js

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:306:11)
      at node_modules/@typescript-eslint/eslint-plugin/src/util/getESLintCoreRule.ts:48:11
      at Object.<anonymous> (node_modules/@typescript-eslint/eslint-plugin/src/rules/brace-style.ts:10:35)

  ● Standalone configs › eslint-config/typescript

    Failed to load config "plugin:@typescript-eslint/eslint-recommended" to extend from.
    Referenced from: CLIOptions

       7 |
       8 | async function runEslint(code: string, overrideConfig: Linter.ConfigOverride, filePath?: string): Promise<Linter.LintMessage[]> {
    >  9 |   const eslint = new ESLint({useEslintrc: false, overrideConfig});
         |                  ^
      10 |
      11 |   const [{messages}] = await eslint.lintText(code, {filePath});
      12 |

      at configInvalidError (packages/eslint-config/node_modules/@eslint/eslintrc/lib/config-array-factory.js:299:9)
      at ConfigArrayFactory._loadExtendedPluginConfig (packages/eslint-config/node_modules/@eslint/eslintrc/lib/config-array-factory.js:884:31)
      at ConfigArrayFactory._loadExtends (packages/eslint-config/node_modules/@eslint/eslintrc/lib/config-array-factory.js:792:29)
      at ConfigArrayFactory._normalizeObjectConfigDataBody (packages/eslint-config/node_modules/@eslint/eslintrc/lib/config-array-factory.js:733:25)
          at _normalizeObjectConfigDataBody.next (<anonymous>)
      at ConfigArrayFactory._normalizeObjectConfigData (packages/eslint-config/node_modules/@eslint/eslintrc/lib/config-array-factory.js:678:20)
          at _normalizeObjectConfigData.next (<anonymous>)
      at ConfigArrayFactory.create (packages/eslint-config/node_modules/@eslint/eslintrc/lib/config-array-factory.js:473:16)
      at createCLIConfigArray (packages/eslint-config/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:168:47)
      at CascadingConfigArrayFactory.clearCache (packages/eslint-config/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:340:32)
      at new ESLint (packages/eslint-config/node_modules/eslint/lib/eslint/eslint.js:448:32)
      at packages/eslint-config/test/eslint.test.ts:9:18
      at step (packages/eslint-config/test/eslint.test.ts:44:23)
      at Object.next (packages/eslint-config/test/eslint.test.ts:25:53)
      at packages/eslint-config/test/eslint.test.ts:19:71
      at Object.<anonymous>.__awaiter (packages/eslint-config/test/eslint.test.ts:15:12)
      at runEslint (packages/eslint-config/test/eslint.test.ts:55:12)
      at packages/eslint-config/test/eslint.test.ts:47:26
      at step (packages/eslint-config/test/eslint.test.ts:44:23)
      at Object.next (packages/eslint-config/test/eslint.test.ts:25:53)
      at packages/eslint-config/test/eslint.test.ts:19:71
      at Object.<anonymous>.__awaiter (packages/eslint-config/test/eslint.test.ts:15:12)
      at Object.<anonymous> (packages/eslint-config/test/eslint.test.ts:39:36)

Test Suites: 1 failed, 7 passed, 8 total
Tests:       2 failed, 24 passed, 26 total
Snapshots:   0 total
Time:        5.539 s

```

**Comment by edloidas** [comment]
`jest` & `ts-jest` of `v26` do not support ESM, thus config can't load some plugins.
https://github.com/typescript-eslint/typescript-eslint/issues/4210#issuecomment-981203332
